import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalNavBar from "../components/GlobalNavBar/GlobalNavBar";
import GlobalFooter from "../components/GlobalFooter/GlobalFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNavBar />
        {children}
        <GlobalFooter />
      </body>
    </html>
  );
}
